受け入れ人数追加
Code-for-Funabashi/map pull request #125
Opened 2022-02-27 14:33 UTC by aca-ta

2022-02-27 14:33 UTC, aca-ta commented on package.json
> +  "browserslist": [
ビルド通らなかったため変更した
https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat/67574280#67574280

2022-07-10 01:40 UTC, aca-ta commented on src/pages/Index/Index.tsx
> +    url: "https://raw.githubusercontent.com/Code-for-Funabashi/open-data-parser/feature/hoikuen-latlng/data/kosodate-map/hoikuen.json",
https://github.com/Code-for-Funabashi/open-data-parser/pull/20 がマージされたら修正する

2022-07-10 01:42 UTC, aca-ta commented
- [ ] どの年月の情報かを把握できるようにする。

2022-07-10 05:44 UTC, aca-ta commented on src/components/Map/PolygonLayer.tsx
> -const loadFeatures = async (url: string) => {
`util.js` にて共通化した

2022-07-10 13:30 UTC, kyoya0819 commented on src/components/Map/tooltip.scss
> +* {
リセットCSSの記述は、新たに`src/styles/reset.scss`を作成しそこで指定するか、index.cssで指定した方が良いと思います。

2022-07-10 13:30 UTC, kyoya0819 commented on src/components/Map/tooltip.scss
> +.card {
単体でスタイルを成り立たせるために、一部Reafletのスタイルとぶつかってしまい違和感があるので、修正版のコードを作成しました。

```scss
// LeafletのリセットCSS
.leaflet-popup-content-wrapper {
    padding: 0;
    box-shadow: none;
}

.leaflet-popup-content {
    position: relative;
    margin: 0;
}

.leaflet-popup-close-button {
    top: calc(((.9rem * 1.4 + 1.5rem) - 1rem) / 2) !important;
    right: .5rem !important;
    display: block;
    width: 1rem !important;
    height: 1rem !important;
    color: #222 !important;

    &::before, &::after {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        display: block;
        width: 1rem;
        height: 2px;
        background: #FFF;
    }

    &::after {
        transform: translate(-50%, -50%) rotate(45deg);
    }

    &::before {
        transform: translate(-50%, -50%) rotate(-45deg);
    }
}

.card {
    border-radius: .75rem;
    overflow: hidden;
    display: block;
    width: 100%;
    border: none;

    & > .name {
        padding: .75rem 2rem;
        background: #222;
        color: #FFF;
        text-align: center;
        font-size: .9rem;
    }

    & > .contents {
        font-size: .9rem;
        padding: .75rem 1rem;

        div {
            margin-bottom: .75rem;

            .title {
                margin-bottom: .375rem;
            }

            .contents {
                font-size: .8rem;
            }
        }

        .categories {
            display: flex;
            flex-wrap: wrap;
            font-size: .8rem;

            .category {
                padding: .375rem .75rem;
                background: #EEE;
                border-radius: 9999px;
                margin-right: .35rem;
                margin-bottom: .5rem;
                font-size: .8rem;

                &:last-of-type {
                    margin-right: 0;
                }
            }
        }

        .postal-code {
            display: inline-block;
            font-size: .7rem;
        }

        .capacities {

            ul {
                display: flex;
                list-style: none;
                margin-bottom: -.4rem;

                li {
                    margin-bottom: .4rem;
                    margin-right: 1rem;
                    font-size: .8rem;

                    &:last-of-type {
                        margin-right: 0;
                    }
                }
            }
        }
    }
}
```

2022-07-10 13:30 UTC, kyoya0819 commented on src/components/Map/Tooltip.tsx
> +import "./tooltip.scss";
通常のSassではなく、CSS Module（*.module.scss）の方が良いと思われます。

2022-07-10 13:31 UTC, kyoya0819 commented
個人的に気になったところをコメントしました。ご確認いただけますと幸いです。
他にももう少しある（ディレクトリ構造や各パッケージのバージョン等々）のですが、多分PRを分けた方がいいので後で別でissueを立てておきます。

2022-07-11 01:08 UTC, aca-ta commented on src/components/Map/Tooltip.tsx
> +import "./tooltip.scss";
詳しくないのでネットで調べて見よう見まねでやってみたんですが、
こちらであってますかね？
https://github.com/Code-for-Funabashi/map/pull/125/commits/015fa7367ebe709e0ec19f0b8cd8a221a7489a58

2022-07-11 01:10 UTC, kyoya0819 commented on src/components/Map/Tooltip.tsx
> +import "./tooltip.scss";
はい。それで問題ないと思います。

2022-07-11 01:17 UTC, aca-ta commented on src/components/Map/tooltip.scss
> +.card {
ありがとうございます、反映しました 🙏 
https://github.com/Code-for-Funabashi/map/pull/125/commits/7bb9b4548e6d0708c83321be51b4b00eb2281da5

2022-07-11 01:21 UTC, aca-ta commented on src/components/Map/tooltip.scss
> +* {
@kyoya0819 
cssに無知なので素朴に聞いてしまうのですが、
body.font-familyについて `index.css` と `tooltip.scss` の両方に定義されているんですが、
これはどちらをどのように適用させるのが良いでしょうか。。？
(index.cssの方を削除してtooltip.scssの方の記述をindex.cssに移動させる、またはtooltip.scssの方はtooltipのみに適用させる、などを想像しています。)

https://github.com/Code-for-Funabashi/map/blob/7bb9b4548e6d0708c83321be51b4b00eb2281da5/src/index.css#L3-L7

https://github.com/Code-for-Funabashi/map/blob/feature/hoikuen-latlng/src/components/Map/tooltip.module.scss#L7-L9

2022-07-18 03:33 UTC, kyoya0819 commented on src/components/Map/tooltip.scss
> +* {
`tooltip.scss`には`font-family`の設定は記述せずに、`index.scss`のみに記述する形になると思います。
その中で`tooltip.scss`か`index.scss`のどちらの`font-family`を採用するかは議論の余地がありますが。。

2022-07-23 14:59 UTC, aca-ta commented on src/components/Map/tooltip.scss
> +* {
`tooltip.scss` の方のfont-familyを採用してみましたが、いかがでしょう？
元の状態から大きな変化は無いように見えますが、、

2022-07-24 21:43 UTC, kyoya0819 commented on src/components/Map/tooltip.scss
> +* {
LGTMです！！
（おそらく、見た目が変わるのはごくごく限られた環境ですので。。

2022-07-24 21:43 UTC, kyoya0819 approved these changes

2022-07-24 21:53 UTC, kyoya0819 requested changes

2022-07-24 21:53 UTC, kyoya0819 commented on package.json
> +    "node-sass": "^6.0.1",
すみません、見落としていました。
おそらく機能的に`sass`と被ってしまうので、`node-sass`は不要だと思います。

2022-07-24 21:54 UTC, kyoya0819 commented on package.json
> +    "node-sass": "^6.0.1",
すみません。見落としていました。
`sass`と機能が被ってしまうため`node-sass`は不要だと思います。

2022-07-25 00:32 UTC, aca-ta commented on package.json
> +    "node-sass": "^6.0.1",
なるほど、、
削除しました！
https://github.com/Code-for-Funabashi/map/pull/125/commits/1a16c44b0a3a9ca9914e75caa99aaa6db2c5c77a

2022-07-25 00:35 UTC, kyoya0819 approved these changes

2022-07-25 00:35 UTC, aca-ta commented
レビューありがとうございました。
マージします！

2022-07-25 00:36 UTC, merged