Feature/add gakku
Code-for-Funabashi/map pull request #42
Opened 2021-09-22 08:13 UTC by Jumpo-523

## 注意事項
- GeoJson クラスの仕様理解が及ばず、とりあえずPolygonモジュールを利用しました!

open-data-parser と合わせてreviewお願いいたします。

2021-09-24 06:20 UTC, aca-ta requested changes
コメントしましたー

2021-09-24 06:20 UTC, aca-ta commented on src/components/PolygonLayer.tsx
> +  coordinates: number[][][];
Leaflet.LatLngExpression[][][] が正しいと思います。
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3940eb25e108a2115f8240bffffa6148242942c1/types/leaflet/index.d.ts#L163

2021-09-24 06:20 UTC, aca-ta commented on src/components/KosodateMap.tsx
> +    option: shogakokkuOptions,
Iconsは定義するものが多いのと再利用性を考慮して別に定義しましたが、
こちらは切り出す必要は無いかなと思いました。

2021-09-24 07:26 UTC, aca-ta commented
元データの問題かもしれないですが、このあたりちょっと怪しいですね。

![スクリーンショット 2021-09-24 162535](https://user-images.githubusercontent.com/5401476/134635156-59da3d60-bb8a-4dfc-8f99-e53e3d22f0f2.png)

2021-09-26 01:41 UTC, Jumpo-523 reviewed
ありがとうございます！
学区外になってしまっている箇所は調査してみます！
（以前塚本さんにQGISで見てもらったときは隙間なく学区表示されていたのを考えると、おそらくpythonでparseする際におかしくしてしまっているような気がしています）

2021-09-26 01:41 UTC, Jumpo-523 commented on src/components/KosodateMap.tsx
> +    option: shogakokkuOptions,
小学校区、中学校区など今後表示したいエリアが増えてきた時に色変えると分かりやすいかなと思っておりました。（まぁ同時に表示することはないから、、なくてもいいっちゃいいのかもしれませんが...）
ここは本日お話させてください！

2021-09-26 03:27 UTC, aca-ta commented on src/components/KosodateMap.tsx
> +    option: shogakokkuOptions,
あ、optionを変数にして別モジュールに切り出す必要は無いかな、という意味でした。

2021-09-26 07:53 UTC, Jumpo-523 commented on src/components/KosodateMap.tsx
> +    option: shogakokkuOptions,
なるほど、理解しました。OKです！

2021-10-13 09:00 UTC, aca-ta commented on src/components/PolygonLayer.tsx
> +    <Area
keyが指定されないのでエラーが発生しますね。
こちらと同じ事象です。
https://github.com/Code-for-Funabashi/map/issues/61#issue-1024052673

2021-10-16 03:24 UTC, Jumpo-523 commented
すいません、体調崩して作業止めてました。
[この話](https://github.com/Code-for-Funabashi/map/pull/60)ですよね、先に[#60](https://github.com/Code-for-Funabashi/map/pull/60)をマージしていただいて、こちらのPRはディレクトリ構成を修正してからマージ、でもいいのかなと思いましたがいかがでしょうか？

2021-10-16 03:38 UTC, kyoya0819 commented
急かすような発言をしてしまい申し訳がございません。
#60 をマージさせていただきます。ありがとうございます。

2021-12-19 16:29 UTC, j-takurou commented on src/components/PolygonLayer.tsx
> +    <Area
こちら
`<LayersControl.Overlay name={item.type} key={index} checked>`
LayersControl.Overlayの引数設定だけで起きる事象ではないんですかね？？

2021-12-26 12:31 UTC, aca-ta reviewed
コメントしました！

2021-12-26 12:31 UTC, aca-ta commented on src/types/Polygon.ts
> +    type: string;
インデント幅がここだけ4になっています。

2021-12-26 12:31 UTC, aca-ta commented on src/components/PolygonLayer.tsx
> +export interface PolygonMeta {
src/types/Polygon.ts にも定義されています。
こちらは消し忘れですか？

2021-12-26 12:31 UTC, aca-ta commented on src/components/PolygonLayer.tsx
> +    <Area
https://github.com/Code-for-Funabashi/map/pull/42/files#diff-e955ebfd941a43f6d95087aa51204137bfbcd3665256505cbbf283f4ff766e78R18-R20
ここを以下のようにするのはいかがでしょう
```ts
  return features.map((feature, idx) => (
    <Polygon
      polygon={feature}
      option={polygonMeta.option}
      // マルチポリゴンを使っていないためnameがユニークにならないので、idxを利用
      key={idx}
    />
  ));

```

2021-12-29 14:05 UTC, j-takurou commented on src/types/Polygon.ts
> +    type: string;
ありがとうございます！修正します。

2021-12-29 14:05 UTC, j-takurou commented on src/components/PolygonLayer.tsx
> +export interface PolygonMeta {
すみません消し忘れです。修正しました！

2021-12-29 14:07 UTC, j-takurou commented
@aca-ta 修正しました。いただいたコードで解決しました！
(下記コメントで問題理解しました。ありがとうございます。。！)
> マルチポリゴンを使っていないためnameがユニークにならないので、idxを利用

2021-12-29 14:30 UTC, j-takurou commented
種別情報が表示されてなかったので、updateしました。mm
<img width="264" alt="Screen Shot 2021-12-29 at 23 29 04" src="https://user-images.githubusercontent.com/29911671/147672433-9e384d75-9b0a-4ca0-b74e-6976f955eef1.png">

- 表示されていなかった理由：
    - gakku.jsonのスキームである`PolygonInfo`内に現在用意していないtypeを入れてしまっていました。(下記)
```ts
export interface PolygonInfo {
  type: any;
  name: string;
  coordinates: LatLngExpression[][][];
  }
```
なので、typeは、Point クラス同様、Metaクラスから参照するように修正しました。

2021-12-30 13:34 UTC, aca-ta commented on src/components/Map/PolygonLayer.tsx
> +      key={idx}
`// マルチポリゴンを使っていないためnameがユニークにならないので、idxを利用` のコメントは残しておいてほしいですー

2022-01-02 10:29 UTC, j-takurou commented on src/components/Map/PolygonLayer.tsx
> +      key={idx}
承知しました！

2022-01-02 12:06 UTC, aca-ta approved these changes
LGTMです！色々とご対応いただきありがとうございました！

2022-02-06 03:47 UTC, merged